/**
 * Production server entry — wraps the Vite-built Fresh handler with the
 * Polaris hostname-driven path rewrite so admin requests on
 * `manage.polaris.express/<path>` are dispatched to `routes/admin/<path>`
 * without exposing the `/admin` prefix in the URL.
 *
 * Why this file exists: `vite build` emits `_fresh/server.js` as a thin
 * wrapper that exports `{ fetch: server.fetch }` directly. Calling
 * `deno serve _fresh/server.js` therefore bypasses the
 * `polarisCreateFetchHandler()` wrapper exported by `main.ts`. Production
 * needs a stable server entry that combines:
 *
 *   1. The Vite-built Fresh handler (route table, islands, SSR runtime)
 *   2. The Polaris path-rewrite layer (admin host → /admin/* dispatch)
 *
 * `deno task start` invokes this file via `deno serve -A prod-server.ts`.
 *
 * NOTE: this file imports the Fresh build artifact at `_fresh/server.js`,
 * so it requires `deno task build` to have run before serving. The
 * Dockerfile runs the build during image construction so the artifact is
 * present at runtime.
 */

import {
  classifyAdminHostname,
  classifyCustomerHostname,
  isShellOrApiPath,
  rewriteRequestForSurface,
} from "./src/lib/hostname-dispatch.ts";

// Dynamic import so `deno check` doesn't type-walk into the Vite build
// output. The artifact is generated by `deno task build` before this file
// is served in production.
type FetchFn = (
  req: Request,
  info?: Deno.ServeHandlerInfo,
) => Response | Promise<Response>;
type FreshBuildModule = { default: { fetch: FetchFn } };
const buildSpecifier = "./_fresh/server.js";
const freshBuild =
  ((await import(/* @vite-ignore */ buildSpecifier)) as FreshBuildModule)
    .default;

/**
 * Skip the path rewrite for static assets, Fresh build internals, and
 * shared API paths. Mirrors the same predicate `main.ts` uses for dev.
 */
function shouldRewriteAdminPath(pathname: string): boolean {
  // Shared with main.ts via isShellOrApiPath — single source of truth for
  // the static/shell whitelist.
  if (isShellOrApiPath(pathname)) return false;
  // Apple Universal Links manifest is fetched WITHOUT auth from the
  // registered domain root (no /admin prefix), so the rewrite must skip it.
  if (pathname.startsWith("/.well-known/")) return false;
  if (pathname === "/admin" || pathname.startsWith("/admin/")) return false;
  return true;
}

const innerFetch: FetchFn = freshBuild.fetch;

export default {
  async fetch(req: Request, info?: Deno.ServeHandlerInfo): Promise<Response> {
    const url = new URL(req.url);
    const hostname = url.hostname.toLowerCase();
    let rewritten = req;
    if (
      classifyAdminHostname(hostname) === "admin" &&
      shouldRewriteAdminPath(url.pathname)
    ) {
      rewritten = rewriteRequestForSurface(req, url, "admin");
    } else if (classifyCustomerHostname(hostname) === "customer") {
      // Customer surface uses original paths; no rewrite.
    }
    return await innerFetch(rewritten, info);
  },
};
