import {
  type AnyPgColumn,
  bigint,
  boolean,
  check,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  serial,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

// ============================================================================
// BETTERAUTH TABLES
// These tables are required by BetterAuth for authentication
// ============================================================================

/**
 * Users table - stores user accounts
 * BetterAuth manages this table for authentication
 *
 * Polaris Track A:
 *   - default role flipped from 'admin' → 'customer' (migration 0019)
 *   - CHECK constraint added enforcing role IN ('admin','customer')
 *   - email uniqueness now enforced via the case-insensitive functional
 *     index `users_email_lower_unique` on `LOWER(email)` (migration 0027).
 *     The `.unique()` Drizzle marker is dropped here so the schema diff
 *     stays in sync; the older case-sensitive unique constraint was
 *     dropped in 0027.
 *   - `onboarded_at` flipped by `POST /api/customer/onboarded` once the
 *     first-run dashboard tour completes (migration 0020).
 */
export const users = pgTable("users", {
  id: text("id").primaryKey(), // UUID generated by BetterAuth
  name: text("name"),
  // NULL allowed for customer accounts auto-provisioned from a Lago
  // customer that has no email. Admin-created users always have one.
  // Migration 0028 dropped the NOT NULL constraint.
  email: text("email"),
  emailVerified: boolean("email_verified").default(false),
  image: text("image"),
  role: text("role").notNull().default("customer"), // "admin" | "customer"
  // Direct link to the Lago customer this user was provisioned from. Added
  // in migration 0030 so the no-email provisioning path is idempotent: the
  // reconcile loop used to create a fresh `users` row every time it saw a
  // Lago customer without an email (no sibling mapping + no email lookup
  // fell through to a blind INSERT), producing one duplicate row per run.
  // Uniqueness is enforced by a partial index in the migration file.
  lagoCustomerExternalId: text("lago_customer_external_id"),
  onboardedAt: timestamp("onboarded_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
}, (table) => [
  // Functional case-insensitive unique index (migration 0027). Drizzle
  // serializes this as `users_email_lower_unique`; the raw SQL in the
  // migration file matches the same name.
  uniqueIndex("users_email_lower_unique").on(sql`lower(${table.email})`),
  check(
    "users_role_check",
    sql`${table.role} IN ('admin', 'customer')`,
  ),
]);

/**
 * Sessions table - stores active user sessions
 */
export const sessions = pgTable("sessions", {
  id: text("id").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  token: text("token").notNull().unique(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

/**
 * Accounts table - stores OAuth provider accounts
 * Also used for email/password credentials
 */
export const accounts = pgTable("accounts", {
  id: text("id").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(), // "credential" for email/password
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at", {
    withTimezone: true,
  }),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at", {
    withTimezone: true,
  }),
  scope: text("scope"),
  password: text("password"), // Hashed password for credential provider
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

/**
 * Verifications table - stores email verification tokens
 */
export const verifications = pgTable("verifications", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(), // Email address
  value: text("value").notNull(), // Verification token
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

// ============================================================================
// APPLICATION TABLES
// Custom tables for ExpresSync
// ============================================================================

/**
 * User Mappings - Links StEvE OCPP tags to Lago customers/subscriptions
 *
 * This is the core mapping table that enables billing.
 * Each row links one OCPP ID tag to one Lago subscription.
 */
export const userMappings = pgTable("user_mappings", {
  id: serial("id").primaryKey(),

  // StEvE identifiers
  steveOcppTagPk: integer("steve_ocpp_tag_pk").notNull().unique(),
  steveOcppIdTag: text("steve_ocpp_id_tag").notNull(),

  // Lago identifiers (nullable until mapping is complete)
  lagoCustomerExternalId: text("lago_customer_external_id"),
  lagoSubscriptionExternalId: text("lago_subscription_external_id"),

  // Display information
  displayName: text("display_name"),
  notes: text("notes"),

  // === Phase I: tag type ===
  // Form-factor category — see `src/lib/types/tags.ts` (TAG_TYPES) for the
  // allowed values. CHECK constraint enforced at the DB level; keep this
  // column and `TAG_TYPES` in sync.
  tagType: text("tag_type").notNull().default("other"),

  // === Phase P2: billing profile ===
  // 'standard' users get normal usage billing. 'comped' users have the
  // `free_charging` 100%-off coupon applied in Lago (reconciled on flip).
  billingTier: text("billing_tier").notNull().default("standard"),
  // Running count of EV cards / tokens issued to this user — used to drive
  // "first card free" logic (legacy) and to size the issued_cards audit.
  cardsIssued: integer("cards_issued").notNull().default(0),

  // Status
  isActive: boolean("is_active").default(true),

  // === Polaris OCPP-tag invariants ===
  // SteVe's `ocpp_tag` table has its own `parent_id_tag` and `expiry_date`
  // columns; SteVe stores them as the source of truth for the OCPP wire
  // semantics. We mirror them here so `syncSingleTagToSteve` (which does a
  // full PUT of the tag on every is_active toggle) doesn't have to issue
  // an extra GET to preserve those fields. Without these, the inline sync
  // would clobber `parent_id_tag` to NULL on every link/unlink/metadata
  // edit.
  // - `steveParentIdTag`: nullable; matches SteVe's `parent_id_tag`. The
  //   parent _must_ exist in SteVe before we can set it.
  // - `steveExpiryDate`: nullable; matches SteVe's `expiry_date`.
  steveParentIdTag: text("steve_parent_id_tag"),
  steveExpiryDate: timestamp("steve_expiry_date", { withTimezone: true }),

  // Polaris Track A: link to the customer account that owns this mapping
  // (nullable; ON DELETE SET NULL). The trigger from migration 0018 enforces
  // that the referenced user MUST have role='customer' (admins cannot own
  // mappings). Migration 0026 enforces consistency: all mappings sharing a
  // `lago_customer_external_id` must share the same user_id.
  userId: text("user_id").references(() => users.id, { onDelete: "set null" }),

  // Timestamps
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
}, (table) => [
  index("idx_user_mappings_is_active").on(table.isActive),
  index("idx_user_mappings_lago_customer_external_id").on(
    table.lagoCustomerExternalId,
  ),
  index("idx_user_mappings_user_id").on(table.userId),
  check(
    "user_mappings_billing_tier_check",
    sql`${table.billingTier} IN ('standard', 'comped')`,
  ),
]);

/**
 * Issued Cards — audit of EV-card/token issuances per mapping.
 *
 * Written from `POST /api/mapping/issue-card`. `billing_mode` captures the
 * operator's choice at issuance time:
 *   - `charged`: a one-off Lago invoice was created with the `ev_card`
 *     add-on ($3). `lago_invoice_id` is set.
 *   - `no_cost`: same one-off invoice, plus the `free_card` coupon applied.
 *     Both `lago_invoice_id` and `lago_applied_coupon_id` are set.
 *   - `skipped_sync`: no Lago call was made. Both FKs are null.
 *
 * `sync_error` is populated when a Lago call failed after the local row was
 * written, so the operator can retry from the UI.
 */
export const issuedCards = pgTable("issued_cards", {
  id: serial("id").primaryKey(),
  userMappingId: integer("user_mapping_id")
    .notNull()
    .references(() => userMappings.id, { onDelete: "cascade" }),
  /**
   * Physical form factor of the card / token / fob. Limited to the three
   * issuable options in the Add Card UX; broader `tag_type` values (app /
   * guest_qr / phone_nfc / other) are never produced by this flow.
   */
  cardType: text("card_type").notNull().default("ev_card"),
  billingMode: text("billing_mode").notNull(),
  lagoInvoiceId: text("lago_invoice_id"),
  lagoAppliedCouponId: text("lago_applied_coupon_id"),
  note: text("note"),
  syncError: text("sync_error"),
  issuedBy: text("issued_by").references(() => users.id),
  issuedAt: timestamp("issued_at", { withTimezone: true }).notNull()
    .defaultNow(),
}, (table) => [
  index("idx_issued_cards_user_mapping_id").on(table.userMappingId),
  index("idx_issued_cards_issued_at").on(table.issuedAt),
  check(
    "issued_cards_billing_mode_check",
    sql`${table.billingMode} IN ('charged', 'no_cost', 'skipped_sync')`,
  ),
  check(
    "issued_cards_card_type_check",
    sql`${table.cardType} IN ('ev_card', 'keytag', 'sticker')`,
  ),
]);

export type IssuedCard = typeof issuedCards.$inferSelect;
export type NewIssuedCard = typeof issuedCards.$inferInsert;

/**
 * Sync Runs - Tracks each sync execution
 *
 * Stores metadata about each sync run for debugging and monitoring.
 */
export const syncRuns = pgTable("sync_runs", {
  id: serial("id").primaryKey(),

  // Timing
  startedAt: timestamp("started_at", { withTimezone: true }).notNull()
    .defaultNow(),
  completedAt: timestamp("completed_at", { withTimezone: true }),

  // Status: "running" | "completed" | "failed"
  status: text("status").notNull().default("running"),

  // Segment statuses: "success" | "warning" | "error" | "skipped" | null (not run yet)
  tagLinkingStatus: text("tag_linking_status"),
  transactionSyncStatus: text("transaction_sync_status"),

  // Statistics
  transactionsProcessed: integer("transactions_processed").default(0),
  eventsCreated: integer("events_created").default(0),

  // Tag linking statistics
  tagsActivated: integer("tags_activated").default(0),
  tagsDeactivated: integer("tags_deactivated").default(0),
  tagsUnchanged: integer("tags_unchanged").default(0),

  // Error tracking (JSON array of error messages)
  errors: text("errors"),
}, (table) => [
  index("idx_sync_runs_status").on(table.status),
  index("idx_sync_runs_started_at").on(table.startedAt),
]);

/**
 * Sync Run Logs - Detailed logs for each sync run segment
 *
 * Tracks individual operations within each sync segment for debugging.
 * Logs are timestamped and colored by status level.
 */
export const syncRunLogs = pgTable("sync_run_logs", {
  id: serial("id").primaryKey(),

  // Reference to parent sync run
  syncRunId: integer("sync_run_id")
    .notNull()
    .references(() => syncRuns.id, { onDelete: "cascade" }),

  // Segment: "tag_linking" | "transaction_sync"
  segment: text("segment").notNull(),

  // Log level: "info" | "warn" | "error" | "debug"
  level: text("level").notNull().default("info"),

  // Log message
  message: text("message").notNull(),

  // Additional context (JSON)
  context: text("context"),

  // Timestamp
  createdAt: timestamp("created_at", { withTimezone: true }).notNull()
    .defaultNow(),
}, (table) => [
  index("idx_sync_run_logs_sync_run_id_created_at").on(
    table.syncRunId,
    table.createdAt,
  ),
]);

/**
 * Transaction Sync State - Tracks incremental meter readings per transaction
 *
 * This table enables incremental billing by storing the last synced
 * meter value for each StEvE transaction. This allows us to:
 * - Bill for in-progress charging sessions
 * - Calculate deltas (only bill for new usage since last sync)
 * - Mark transactions as finalized when completed
 */
export const transactionSyncState = pgTable("transaction_sync_state", {
  id: serial("id").primaryKey(),

  // StEvE transaction reference
  steveTransactionId: integer("steve_transaction_id").notNull().unique(),

  // Last synced meter value (in Wh)
  // Used as the base for calculating the next delta
  lastSyncedMeterValue: integer("last_synced_meter_value").notNull(),

  // Total kWh billed so far for this transaction
  totalKwhBilled: numeric("total_kwh_billed", { precision: 12, scale: 6 })
    .default("0"),

  // Reference to the last sync run that updated this
  lastSyncRunId: integer("last_sync_run_id").references(() => syncRuns.id),

  // True when the transaction is complete and no more billing will occur
  isFinalized: boolean("is_finalized").default(false),

  // Timestamps
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

/**
 * Synced Transaction Events - Audit log of all Lago events sent
 *
 * Each row represents one usage event sent to Lago.
 * For incremental billing, multiple events may be sent per StEvE transaction.
 */
export const syncedTransactionEvents = pgTable("synced_transaction_events", {
  id: serial("id").primaryKey(),

  // StEvE reference
  steveTransactionId: integer("steve_transaction_id").notNull(),

  // Link to sync state
  transactionSyncStateId: integer("transaction_sync_state_id")
    .references(() => transactionSyncState.id),

  // Lago event details
  lagoEventTransactionId: text("lago_event_transaction_id").notNull().unique(),

  // User mapping reference
  userMappingId: integer("user_mapping_id")
    .references(() => userMappings.id),

  // Usage details for this event (delta, not total)
  kwhDelta: numeric("kwh_delta", { precision: 12, scale: 6 }).notNull(),

  // Meter values at time of this event
  meterValueFrom: integer("meter_value_from").notNull(), // Base (Wh)
  meterValueTo: integer("meter_value_to").notNull(), // Current (Wh)

  // Whether this was the final event for the transaction
  isFinal: boolean("is_final").default(false),

  // Reference to sync run
  syncRunId: integer("sync_run_id")
    .references(() => syncRuns.id),

  // When this event was created/sent
  syncedAt: timestamp("synced_at", { withTimezone: true }).defaultNow(),
}, (table) => [
  index("idx_synced_transaction_events_sync_run_id").on(table.syncRunId),
  index("idx_synced_transaction_events_steve_transaction_id").on(
    table.steveTransactionId,
  ),
]);

// ============================================================================
// TYPE EXPORTS
// ============================================================================

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;

export type Session = typeof sessions.$inferSelect;
export type NewSession = typeof sessions.$inferInsert;

export type Account = typeof accounts.$inferSelect;
export type NewAccount = typeof accounts.$inferInsert;

export type Verification = typeof verifications.$inferSelect;
export type NewVerification = typeof verifications.$inferInsert;

export type UserMapping = typeof userMappings.$inferSelect;
export type NewUserMapping = typeof userMappings.$inferInsert;

export type SyncRun = typeof syncRuns.$inferSelect;
export type NewSyncRun = typeof syncRuns.$inferInsert;

export type TransactionSyncState = typeof transactionSyncState.$inferSelect;
export type NewTransactionSyncState = typeof transactionSyncState.$inferInsert;

export type SyncedTransactionEvent =
  typeof syncedTransactionEvents.$inferSelect;
export type NewSyncedTransactionEvent =
  typeof syncedTransactionEvents.$inferInsert;

export type SyncRunLog = typeof syncRunLogs.$inferSelect;
export type NewSyncRunLog = typeof syncRunLogs.$inferInsert;

// Sync segment types
export type SyncSegment =
  | "tag_linking"
  | "transaction_sync"
  | "scheduling"
  | "lago_customers"
  | "lago_subscriptions"
  | "lago_plans"
  | "lago_invoices"
  | "lago_wallets"
  | "lago_billable_metrics"
  | "local_reconcile";
export type SyncSegmentStatus = "success" | "warning" | "error" | "skipped";
export type SyncLogLevel = "info" | "warn" | "error" | "debug";

// ============================================================================
// === Phase C: adaptive sync cadence ===
// ============================================================================

/**
 * Sync Schedule State - singleton row (id = 1)
 *
 * Tracks the adaptive sync scheduler's current tier, last activity, hysteresis
 * counter, and optional admin-pinned tier override. All time math is done with
 * DB `now()` (not `Date.now()`) to avoid worker/DB clock skew.
 */
export const syncScheduleState = pgTable("sync_schedule_state", {
  id: integer("id").primaryKey().default(1),
  currentTier: text("current_tier").notNull().default("idle"),
  lastActivityAt: timestamp("last_activity_at", { withTimezone: true }),
  lastEvaluatedAt: timestamp("last_evaluated_at", { withTimezone: true }),
  nextRunAt: timestamp("next_run_at", { withTimezone: true }),
  consecutiveIdleTicks: integer("consecutive_idle_ticks").notNull().default(0),
  pinnedUntil: timestamp("pinned_until", { withTimezone: true }),
  pinnedTier: text("pinned_tier"),
}, (table) => [
  check("sync_schedule_state_singleton", sql`${table.id} = 1`),
  check(
    "sync_schedule_state_current_tier_check",
    sql`${table.currentTier} IN ('active','idle','dormant')`,
  ),
  check(
    "sync_schedule_state_pinned_tier_check",
    sql`${table.pinnedTier} IN ('active','idle','dormant')`,
  ),
]);

/**
 * Tag Change Log - append-only audit of tag modifications detected during sync
 *
 * Written by `tag-sync.service` before the StEvE write so activity is recorded
 * even if the upstream call fails. Feeds the scheduler's "any activity in
 * the last 30 days" signal.
 */
export const tagChangeLog = pgTable("tag_change_log", {
  id: serial("id").primaryKey(),
  ocppTagPk: integer("ocpp_tag_pk"),
  idTag: text("id_tag").notNull(),
  changeType: text("change_type").notNull(), // "activated" | "deactivated" | "updated" | "created"
  before: jsonb("before"),
  after: jsonb("after"),
  detectedAt: timestamp("detected_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  syncRunId: integer("sync_run_id").references(() => syncRuns.id, {
    onDelete: "set null",
  }),
}, (table) => [
  index("idx_tag_change_log_detected_at").on(table.detectedAt.desc()),
]);

export type SyncScheduleState = typeof syncScheduleState.$inferSelect;
export type NewSyncScheduleState = typeof syncScheduleState.$inferInsert;

export type TagChangeLog = typeof tagChangeLog.$inferSelect;
export type NewTagChangeLog = typeof tagChangeLog.$inferInsert;

export type SyncTier = "active" | "idle" | "dormant";
export type TagChangeType = "activated" | "deactivated" | "updated" | "created";

// ============================================================================
// === Phase B: chargers cache ===
// ============================================================================

/**
 * Chargers Cache - sticky list of known chargers
 *
 * StEvE 3.12.0 has no REST endpoint for listing charge boxes; we derive the
 * roster from distinct transactions + charger_operation_log, and persist it
 * here so the UI has a stable source of truth even when no transactions exist.
 *
 * `form_factor` drives the SVG icon shown in the charger card grid (Phase J).
 * Defaults to `'wallbox'`; admin-editable in the detail page.
 * `last_status`/`last_status_at` are stamped when a TriggerMessage response
 * arrives; beyond 10m the UI dims the status dot, beyond 1h it shows "Offline".
 */
export const chargersCache = pgTable("chargers_cache", {
  chargeBoxId: text("charge_box_id").primaryKey(),
  chargeBoxPk: integer("charge_box_pk"),
  friendlyName: text("friendly_name"),
  formFactor: text("form_factor").notNull().default("wallbox"),
  firstSeenAt: timestamp("first_seen_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  lastStatus: text("last_status"),
  lastStatusAt: timestamp("last_status_at", { withTimezone: true }),
}, (table) => [
  check(
    "chargers_cache_form_factor_check",
    sql`${table.formFactor} IN ('wallbox','pulsar','commander','wall_mount','generic')`,
  ),
  index("idx_chargers_cache_last_seen").on(table.lastSeenAt.desc()),
]);

export type ChargerCache = typeof chargersCache.$inferSelect;
export type NewChargerCache = typeof chargersCache.$inferInsert;

// ============================================================================
// === Phase A: charger operation log ===
// ============================================================================

/**
 * Charger Operation Log — audit + pending tracker for StEvE OCPP operations
 *
 * Every admin-initiated op (RemoteStart/Stop, Unlock, Reserve, TriggerMessage,
 * GetConfiguration, etc.) writes a row here BEFORE the StEvE call so the
 * request is not lost if upstream fails. `task_id` is filled from StEvE's
 * synchronous `{ taskId }` response; the full OCPP round-trip (success/error)
 * is async and may never appear — polling is best-effort.
 *
 * `status` values: 'pending' | 'submitted' | 'failed' | 'completed' | 'dry_run'
 * Destructive operations (Reset, ClearCache, UpdateFirmware, SendLocalList,
 * ClearChargingProfile, ChangeConfiguration) are explicitly NOT exposed — see
 * `ALLOWED_OPERATIONS` in `src/lib/types/steve.ts`.
 */
export const chargerOperationLog = pgTable("charger_operation_log", {
  id: serial("id").primaryKey(),
  chargeBoxId: text("charge_box_id").notNull(),
  operation: text("operation").notNull(),
  params: jsonb("params"),
  taskId: integer("task_id"),
  requestedByUserId: text("requested_by_user_id").references(() => users.id, {
    onDelete: "set null",
  }),
  status: text("status").notNull().default("pending"),
  result: jsonb("result"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  completedAt: timestamp("completed_at", { withTimezone: true }),
}, (table) => [
  index("idx_charger_operation_log_charge_box_created").on(
    table.chargeBoxId,
    table.createdAt.desc(),
  ),
]);

export type ChargerOperationLog = typeof chargerOperationLog.$inferSelect;
export type NewChargerOperationLog = typeof chargerOperationLog.$inferInsert;

// === Phase I: tag type ===
// Re-export from the single source of truth so other modules can pull the
// allowlist + type from `@/src/db/schema.ts` if that's more convenient.
export { TAG_TYPES } from "../lib/types/tags.ts";
export type { TagType } from "../lib/types/tags.ts";

// ============================================================================
// === Phase D: lago webhook events ===
// ============================================================================

/**
 * Lago Webhook Events - append-only audit of every Lago webhook we receive
 *
 * The route handler persists each payload FIRST (so we never lose data even if
 * dispatch throws), then the dispatcher parses with a discriminated-union Zod
 * schema keyed on `webhook_type` and reacts per-type. `processed_at` and
 * `processing_error` are updated in place after dispatch. `notification_fired`
 * is true when the handler triggered an admin alert (Phase K will read this).
 */
export const lagoWebhookEvents = pgTable("lago_webhook_events", {
  id: serial("id").primaryKey(),
  webhookType: text("webhook_type").notNull(),
  objectType: text("object_type"),
  lagoObjectId: text("lago_object_id"),
  externalCustomerId: text("external_customer_id"),
  externalSubscriptionId: text("external_subscription_id"),
  rawPayload: jsonb("raw_payload").notNull(),
  receivedAt: timestamp("received_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  processedAt: timestamp("processed_at", { withTimezone: true }),
  processingError: text("processing_error"),
  notificationFired: boolean("notification_fired").notNull().default(false),
  // === Phase P4: webhook replay tracking (added columns) ===
  replayedAt: timestamp("replayed_at", { withTimezone: true }), // Phase P4: replay tracking
  replayedByUserId: text("replayed_by_user_id").references(() => users.id, {
    onDelete: "set null",
  }), // Phase P4: replay tracking
  replayedFromId: integer("replayed_from_id").references(
    (): AnyPgColumn => lagoWebhookEvents.id,
    { onDelete: "set null" },
  ), // Phase P4: replay tracking
}, (table) => [
  index("idx_lago_webhook_events_type_received").on(
    table.webhookType,
    table.receivedAt.desc(),
  ),
  index("idx_lago_webhook_events_customer_received").on(
    table.externalCustomerId,
    table.receivedAt.desc(),
  ),
  index("idx_lago_webhook_events_replayed_from").on(
    table.replayedFromId,
  ).where(sql`${table.replayedFromId} IS NOT NULL`),
]);

export type LagoWebhookEvent = typeof lagoWebhookEvents.$inferSelect;
export type NewLagoWebhookEvent = typeof lagoWebhookEvents.$inferInsert;

// ============================================================================
// === Phase P3: reservations ===
// ============================================================================

/**
 * Reservations — admin-booked charging windows against a specific
 * (charge_box, connector) using a known StEvE OCPP tag.
 *
 * Time windows are stored in UTC as `timestamptz` and treated as half-open
 * intervals `[start_at, end_at)` for conflict detection; two reservations on
 * the same connector overlap iff `a.start < b.end AND a.end > b.start`.
 *
 * `status` lifecycle (see CHECK):
 *   pending    — row written; StEvE ReserveNow dispatched
 *   confirmed  — StEvE returned a taskId
 *   active     — currently within the window
 *   completed  — window ended naturally
 *   cancelled  — admin or system cancelled
 *   conflicted — overlap detected post-insert
 *   orphaned   — StEvE no longer tracks this reservation
 *
 * `charging_profile_task_id` is populated by the (optional) P5 apply-hook.
 */
export const reservations = pgTable("reservations", {
  id: serial("id").primaryKey(),

  // Charger target
  chargeBoxId: text("charge_box_id").notNull(),
  connectorId: integer("connector_id").notNull(),

  // StEvE tag reference
  steveOcppTagPk: integer("steve_ocpp_tag_pk").notNull(),
  steveOcppIdTag: text("steve_ocpp_id_tag").notNull(),

  // Lago subscription (nullable; drives optional profile hook)
  lagoSubscriptionExternalId: text("lago_subscription_external_id"),

  // Time window (UTC)
  startAt: timestamp("start_at", { withTimezone: true }).notNull(),
  endAt: timestamp("end_at", { withTimezone: true }).notNull(),
  // Cached duration for display + filters
  durationMinutes: integer("duration_minutes").notNull(),

  // Status
  status: text("status").notNull().default("pending"),

  // StEvE integration
  steveReservationId: integer("steve_reservation_id"),
  chargingProfileTaskId: integer("charging_profile_task_id"),

  // Audit
  createdByUserId: text("created_by_user_id").references(() => users.id, {
    onDelete: "set null",
  }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
}, (table) => [
  check(
    "reservations_status_check",
    sql`${table.status} IN ('pending','confirmed','active','completed','cancelled','conflicted','orphaned')`,
  ),
  check(
    "reservations_time_window_check",
    sql`${table.endAt} > ${table.startAt}`,
  ),
  index("idx_reservations_conflict").on(
    table.chargeBoxId,
    table.connectorId,
    table.startAt,
    table.endAt,
  ),
  index("idx_reservations_tag_start").on(
    table.steveOcppTagPk,
    table.startAt.desc(),
  ),
  index("idx_reservations_status_start").on(
    table.status,
    table.startAt.desc(),
  ),
]);

export type Reservation = typeof reservations.$inferSelect;
export type NewReservation = typeof reservations.$inferInsert;

export type ReservationStatus =
  | "pending"
  | "confirmed"
  | "active"
  | "completed"
  | "cancelled"
  | "conflicted"
  | "orphaned";

export const RESERVATION_STATUSES: readonly ReservationStatus[] = [
  "pending",
  "confirmed",
  "active",
  "completed",
  "cancelled",
  "conflicted",
  "orphaned",
] as const;

/** DTO shape consumed by sibling surfaces (Tag/Charger/Link detail). */
export interface ReservationRowDTO {
  id: number;
  chargeBoxId: string;
  /**
   * Operator-set friendly name (mirrored from StEvE description into
   * `chargers_cache.friendly_name`). May be null when the operator has not
   * supplied one — UIs must fall back to `chargeBoxId`.
   */
  friendlyName?: string | null;
  connectorId: number;
  ocppTagPk: number;
  ocppTagId: string;
  startAtIso: string;
  endAtIso: string;
  status: ReservationStatus;
  lagoSubscriptionExternalId: string | null;
  chargingProfileTaskId: number | null;
}

// ============================================================================
// === Phase P1: notifications ===
// ============================================================================

/**
 * Notifications — in-app admin notification feed.
 *
 * Replaces the `notify()` log stub in lago-webhook-handler.service.ts. Each row
 * is a single notification surfaced in the header bell + archive page.
 *
 * Broadcast model (MVP): rows with `admin_user_id = NULL` are visible to every
 * admin. Per-admin routing is a post-MVP iteration — we keep the column so the
 * API surface can stabilize before then.
 *
 * Severity CHECK matches the UI's NotificationSeverityDot mapping:
 *   info → sky, success → emerald, warn → amber, error → rose.
 *
 * `source_type` + `source_id` identify the originating entity so rows can
 * render outlined cross-domain chips and deep-link on click. Known source
 * types: 'invoice' | 'alert' | 'subscription' | 'wallet_transaction' |
 * 'webhook_event' | 'system' (null link) | 'mapping' | 'charger' | 'reservation'.
 *
 * `context` is free-form JSONB for payload fields the row rendering may want
 * (invoice number, external_id, etc.). Never a source of truth.
 */
export const notifications = pgTable("notifications", {
  id: serial("id").primaryKey(),
  kind: text("kind").notNull(),
  severity: text("severity").notNull(),
  title: text("title").notNull(),
  body: text("body").notNull(),
  sourceType: text("source_type"),
  sourceId: text("source_id"),
  context: jsonb("context"),
  adminUserId: text("admin_user_id").references(() => users.id, {
    onDelete: "cascade",
  }),
  // Polaris Track A: routing axis. 'admin' (existing default) keeps the
  // notification in the admin feed only; 'customer' targets a single
  // customer (use admin_user_id to scope to their user_id even though it's
  // misleadingly named — kept for backwards compatibility); 'all' is a
  // broadcast for cross-surface system messages. Existing rows default to
  // 'admin' so nothing leaks at deploy time.
  audience: text("audience").notNull().default("admin"),
  readAt: timestamp("read_at", { withTimezone: true }),
  dismissedAt: timestamp("dismissed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
}, (table) => [
  check(
    "notifications_severity_check",
    sql`${table.severity} IN ('info', 'success', 'warn', 'error')`,
  ),
  check(
    "notifications_audience_check",
    sql`${table.audience} IN ('admin', 'customer', 'all')`,
  ),
  index("idx_notifications_source").on(table.sourceType, table.sourceId),
  index("idx_notifications_created_at").on(table.createdAt.desc()),
  index("idx_notifications_audience").on(table.audience),
]);

export type Notification = typeof notifications.$inferSelect;
export type NewNotification = typeof notifications.$inferInsert;

/** Allowed severity values (keep in sync with CHECK constraint). */
export const NOTIFICATION_SEVERITIES = [
  "info",
  "success",
  "warn",
  "error",
] as const;
export type NotificationSeverityValue =
  (typeof NOTIFICATION_SEVERITIES)[number];

// ============================================================================
// === Phase P5: charging profiles ===
// ============================================================================

/**
 * Charging Profiles - Per-Lago-subscription charging schedule + power cap
 *
 * Primary storage for subscription-level charging profiles (keyed by
 * `lago_subscription_external_id`). A best-effort mirror is written to
 * Lago's subscription metadata; our DB is the source of truth.
 *
 * Presets:
 * - unlimited: no windows, no cap (clears any profile)
 * - offpeak: weekday nights + weekends, no cap within window
 * - cap7kw: 24/7 at 7000W
 * - cap11kw: 24/7 at 11000W
 * - solar: disabled stub (coming soon)
 * - custom: user-defined windows via grid editor
 */
export const chargingProfiles = pgTable("charging_profiles", {
  id: serial("id").primaryKey(),

  /** Lago subscription external ID this profile belongs to (1:1) */
  lagoSubscriptionExternalId: text("lago_subscription_external_id")
    .notNull()
    .unique(),

  /** Preset identifier */
  preset: text("preset").notNull().default("unlimited"),

  /**
   * Time windows for charging allowance (array of {dayOfWeek, startMin, endMin, maxW?})
   * For presets that imply windows (offpeak, custom), this is populated.
   * For 24/7 caps (cap7kw, cap11kw), this is empty and maxWGlobal is used.
   */
  windows: jsonb("windows").notNull().default([]),

  /** Global power cap in Watts (applies 24/7 outside of window overrides) */
  maxWGlobal: integer("max_w_global"),

  /**
   * Monotonic counter used as `chargingProfileId` in OCPP SetChargingProfile
   * calls (enables ClearChargingProfile targeting even though we never
   * expose a destructive clear — we always apply an Unlimited profile).
   */
  ocppChargingProfileId: integer("ocpp_charging_profile_id")
    .notNull()
    .default(1),

  /** Whether last save requested apply-to-active-sessions */
  applyToActiveSessions: boolean("apply_to_active_sessions").default(false),

  /** Last successful Lago metadata mirror timestamp */
  lagoSyncedAt: timestamp("lago_synced_at"),

  /** Last Lago mirror error (informational; doesn't block UI) */
  lagoSyncError: text("lago_sync_error"),

  /** Audit */
  createdByUserId: text("created_by_user_id").references(() => users.id, {
    onDelete: "set null",
  }),
  updatedByUserId: text("updated_by_user_id").references(() => users.id, {
    onDelete: "set null",
  }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (table) => ({
  subscriptionIdx: index("charging_profiles_subscription_idx")
    .on(table.lagoSubscriptionExternalId),
}));

export type ChargingProfile = typeof chargingProfiles.$inferSelect;
export type NewChargingProfile = typeof chargingProfiles.$inferInsert;

export type ChargingProfilePreset =
  | "unlimited"
  | "offpeak"
  | "cap7kw"
  | "cap11kw"
  | "solar"
  | "custom";

/** A charging time-window slot (half-open: [startMin, endMin) within a day) */
export interface ChargingWindow {
  /** 0 = Sunday, 1 = Monday, ... 6 = Saturday */
  dayOfWeek: number;
  /** Minutes from midnight (0-1440) */
  startMin: number;
  /** Minutes from midnight (0-1440; endMin > startMin) */
  endMin: number;
  /** Optional per-window power cap in Watts (overrides maxWGlobal) */
  maxW?: number;
}

// ============================================================================
// === Phase A7a: Postgres-backed rate limiter ===
// ============================================================================

/**
 * Rate Limits - Postgres-backed fixed-window rate limiter
 *
 * Replaces the in-memory `Map` used previously so rate limits survive restarts
 * and work correctly across multiple app instances. Each row represents one
 * (key, windowStart) bucket; `count` is incremented via UPSERT on every hit.
 *
 * Cleanup is handled by a cron job in `sync-worker.ts` which deletes rows
 * whose `updated_at` is older than 120 seconds.
 */
export const rateLimits = pgTable("rate_limits", {
  id: serial("id").primaryKey(),
  key: text("key").notNull(),
  windowStart: timestamp("window_start", { withTimezone: true }).notNull(),
  count: integer("count").notNull().default(1),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
}, (table) => [
  uniqueIndex("rate_limits_key_window_start_unique").on(
    table.key,
    table.windowStart,
  ),
  index("idx_rate_limits_updated_at").on(table.updatedAt),
]);

export type RateLimit = typeof rateLimits.$inferSelect;
export type NewRateLimit = typeof rateLimits.$inferInsert;

// ============================================================================
// === Polaris Track A: authentication audit + impersonation ===
// ============================================================================

/**
 * Auth Audit — append-only log of authentication events.
 *
 * Captures login, logout, magic-link request/consume, scan-login
 * success/failure, password-login failure, capability denial, impersonation
 * start/end, and admin-email-collision attempts. Read by ops dashboards and
 * forensics; never updated in place. Trimmed to the last 90 days by the
 * sync-worker cleanup cron.
 *
 * `email_hash` is sha256(lowercased email); plaintext email is never stored
 * here so an audit-table dump doesn't yield an enumeration set.
 */
export const authAudit = pgTable("auth_audit", {
  id: serial("id").primaryKey(),
  /** Stable event identifier — see `src/lib/audit.ts` for the canonical list. */
  event: text("event").notNull(),
  /** Optional user reference; null for failed logins of unknown users. */
  userId: text("user_id").references(() => users.id, { onDelete: "set null" }),
  /** sha256 of LOWER(email) — never raw email. Optional. */
  emailHash: text("email_hash"),
  ip: text("ip"),
  ua: text("ua"),
  route: text("route"),
  /** Free-form context (event-specific). Never a source of truth. */
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
}, (table) => [
  index("idx_auth_audit_event_time").on(table.event, table.createdAt.desc()),
  index("idx_auth_audit_user").on(table.userId, table.createdAt.desc()),
]);

export type AuthAudit = typeof authAudit.$inferSelect;
export type NewAuthAudit = typeof authAudit.$inferInsert;

/**
 * Magic Link Audit — pairs a hashed token across its issue and consume events.
 *
 * Used to detect:
 *   - tokens issued but never consumed (delivery failure / user behavior)
 *   - tokens consumed from a different IP/UA than they were requested from
 *     (potential interception via email forwarding / shared inbox)
 *   - request floods against a single email
 *
 * Trimmed to 30 days (shorter than auth_audit because tokens themselves
 * expire in 15 min). Both `email_hash` and `token_hash` are sha256 strings;
 * the raw token is sent in the email and never stored here in plaintext.
 */
export const magicLinkAudit = pgTable("magic_link_audit", {
  id: serial("id").primaryKey(),
  emailHash: text("email_hash").notNull(),
  tokenHash: text("token_hash").notNull(),
  requestedIp: text("requested_ip"),
  requestedUa: text("requested_ua"),
  consumedIp: text("consumed_ip"),
  consumedUa: text("consumed_ua"),
  requestedAt: timestamp("requested_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  consumedAt: timestamp("consumed_at", { withTimezone: true }),
}, (table) => [
  index("idx_magic_link_audit_email").on(
    table.emailHash,
    table.requestedAt.desc(),
  ),
  index("idx_magic_link_audit_token").on(table.tokenHash),
]);

export type MagicLinkAudit = typeof magicLinkAudit.$inferSelect;
export type NewMagicLinkAudit = typeof magicLinkAudit.$inferInsert;

/**
 * Impersonation Audit — admin "view as customer" usage log.
 *
 * Each request made under an impersonation session writes one row here so the
 * admin's snooping is reconstructable. The middleware imposes a per-route
 * rate-limit on logging (~1 row/min/route) to prevent bloat from chatty SSE
 * endpoints; busy mutating endpoints get one row each.
 *
 * Both FKs cascade on user delete; if the customer or admin is removed, the
 * audit row goes too. Forensics use cases should snapshot rows out before
 * any user purge.
 */
export const impersonationAudit = pgTable("impersonation_audit", {
  id: serial("id").primaryKey(),
  adminUserId: text("admin_user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  customerUserId: text("customer_user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  route: text("route").notNull(),
  method: text("method").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
}, (table) => [
  index("idx_impersonation_admin").on(
    table.adminUserId,
    table.createdAt.desc(),
  ),
  index("idx_impersonation_customer").on(
    table.customerUserId,
    table.createdAt.desc(),
  ),
]);

export type ImpersonationAudit = typeof impersonationAudit.$inferSelect;
export type NewImpersonationAudit = typeof impersonationAudit.$inferInsert;

// ============================================================================
// IDEMPOTENCY KEYS
//
// Cached responses for state-changing endpoints that opt-in via the
// `Idempotency-Key` request header. The key + route + (optional) userId
// triple identifies a unique attempt; replays return the cached response
// for 24h. The cleanup is best-effort, run from the sync-worker cron.
// ============================================================================
export const idempotencyKeys = pgTable("idempotency_keys", {
  /** Caller-supplied opaque token (typically a UUID). */
  key: text("key").primaryKey(),
  /** Server-side route identifier — keys are scoped per route. */
  route: text("route").notNull(),
  /** Authenticated user (NULL for anonymous endpoints). */
  userId: text("user_id"),
  /** Cached HTTP status. */
  responseStatus: integer("response_status").notNull(),
  /** Cached response body, JSON-encoded. */
  responseBody: jsonb("response_body").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
}, (table) => [
  index("idempotency_keys_created_at_idx").on(table.createdAt),
]);

export type IdempotencyKey = typeof idempotencyKeys.$inferSelect;
export type NewIdempotencyKey = typeof idempotencyKeys.$inferInsert;

/**
 * Single-row breaker state for the Lago webhook dispatch path. The
 * in-process module-level counters survive a deploy by hydrating from
 * this row at startup and writing through on every transition. A
 * multi-replica deployment trips the breaker once and all replicas
 * converge on the next read.
 *
 * Always exactly one row with id=1 — enforced by the CHECK constraint.
 */
export const lagoWebhookBreakerState = pgTable("lago_webhook_breaker_state", {
  id: integer("id").primaryKey(),
  consecutiveFailures: integer("consecutive_failures").notNull().default(0),
  /** epoch ms when the breaker re-arms. NULL when closed. */
  disabledUntilMs: bigint("disabled_until_ms", { mode: "number" }),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export type LagoWebhookBreakerStateRow =
  typeof lagoWebhookBreakerState.$inferSelect;

// ============================================================================
// === Lago entity cache (Lago is source of truth) ===
//
// One row per Lago entity. `payload` carries the full Lago response so the
// UI/services can read fields we haven't denormalized. `deleted_at` is set by
// the periodic reconciler when an entity disappears from Lago; clearing it
// (which any upsert does) re-activates the row, so an entity re-created with
// the same Lago id automatically reappears.
// ============================================================================

export const lagoCustomers = pgTable("lago_customers", {
  lagoId: text("lago_id").primaryKey(),
  externalId: text("external_id").notNull(),
  name: text("name"),
  email: text("email"),
  currency: text("currency"),
  payload: jsonb("payload").notNull(),
  lagoUpdatedAt: timestamp("lago_updated_at", { withTimezone: true }),
  syncedAt: timestamp("synced_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
}, (table) => [
  uniqueIndex("lago_customers_external_id_unique").on(table.externalId),
  index("idx_lago_customers_deleted_at").on(table.deletedAt),
]);

export const lagoSubscriptions = pgTable("lago_subscriptions", {
  lagoId: text("lago_id").primaryKey(),
  externalId: text("external_id").notNull(),
  externalCustomerId: text("external_customer_id"),
  customerLagoId: text("customer_lago_id"),
  planCode: text("plan_code"),
  status: text("status"),
  startedAt: timestamp("started_at", { withTimezone: true }),
  terminatedAt: timestamp("terminated_at", { withTimezone: true }),
  payload: jsonb("payload").notNull(),
  lagoUpdatedAt: timestamp("lago_updated_at", { withTimezone: true }),
  syncedAt: timestamp("synced_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
}, (table) => [
  uniqueIndex("lago_subscriptions_external_id_unique").on(table.externalId),
  index("idx_lago_subscriptions_customer").on(table.externalCustomerId),
  index("idx_lago_subscriptions_status").on(table.status),
  index("idx_lago_subscriptions_deleted_at").on(table.deletedAt),
]);

export const lagoPlans = pgTable("lago_plans", {
  lagoId: text("lago_id").primaryKey(),
  code: text("code").notNull(),
  name: text("name"),
  interval: text("interval"),
  amountCents: integer("amount_cents"),
  currency: text("currency"),
  payload: jsonb("payload").notNull(),
  lagoUpdatedAt: timestamp("lago_updated_at", { withTimezone: true }),
  syncedAt: timestamp("synced_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
}, (table) => [
  uniqueIndex("lago_plans_code_unique").on(table.code),
  index("idx_lago_plans_deleted_at").on(table.deletedAt),
]);

export const lagoInvoices = pgTable("lago_invoices", {
  lagoId: text("lago_id").primaryKey(),
  number: text("number"),
  externalCustomerId: text("external_customer_id"),
  status: text("status"),
  paymentStatus: text("payment_status"),
  invoiceType: text("invoice_type"),
  totalAmountCents: integer("total_amount_cents"),
  currency: text("currency"),
  issuingDate: text("issuing_date"),
  paymentOverdue: boolean("payment_overdue"),
  payload: jsonb("payload").notNull(),
  lagoUpdatedAt: timestamp("lago_updated_at", { withTimezone: true }),
  syncedAt: timestamp("synced_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
}, (table) => [
  index("idx_lago_invoices_customer").on(table.externalCustomerId),
  index("idx_lago_invoices_status").on(table.status),
  index("idx_lago_invoices_payment_status").on(table.paymentStatus),
  index("idx_lago_invoices_deleted_at").on(table.deletedAt),
]);

export const lagoFees = pgTable("lago_fees", {
  lagoId: text("lago_id").primaryKey(),
  invoiceLagoId: text("invoice_lago_id"),
  externalSubscriptionId: text("external_subscription_id"),
  itemCode: text("item_code"),
  itemName: text("item_name"),
  units: numeric("units", { precision: 16, scale: 6 }),
  amountCents: integer("amount_cents"),
  currency: text("currency"),
  payload: jsonb("payload").notNull(),
  syncedAt: timestamp("synced_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
}, (table) => [
  index("idx_lago_fees_invoice").on(table.invoiceLagoId),
  index("idx_lago_fees_subscription").on(table.externalSubscriptionId),
  index("idx_lago_fees_deleted_at").on(table.deletedAt),
]);

export const lagoWallets = pgTable("lago_wallets", {
  lagoId: text("lago_id").primaryKey(),
  externalCustomerId: text("external_customer_id"),
  status: text("status"),
  currency: text("currency"),
  balanceCents: integer("balance_cents"),
  payload: jsonb("payload").notNull(),
  lagoUpdatedAt: timestamp("lago_updated_at", { withTimezone: true }),
  syncedAt: timestamp("synced_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
}, (table) => [
  index("idx_lago_wallets_customer").on(table.externalCustomerId),
  index("idx_lago_wallets_deleted_at").on(table.deletedAt),
]);

export const lagoBillableMetrics = pgTable("lago_billable_metrics", {
  lagoId: text("lago_id").primaryKey(),
  code: text("code").notNull(),
  name: text("name"),
  aggregationType: text("aggregation_type"),
  fieldName: text("field_name"),
  recurring: boolean("recurring"),
  payload: jsonb("payload").notNull(),
  syncedAt: timestamp("synced_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
}, (table) => [
  uniqueIndex("lago_billable_metrics_code_unique").on(table.code),
  index("idx_lago_billable_metrics_deleted_at").on(table.deletedAt),
]);

export type LagoCustomerRow = typeof lagoCustomers.$inferSelect;
export type NewLagoCustomerRow = typeof lagoCustomers.$inferInsert;
export type LagoSubscriptionRow = typeof lagoSubscriptions.$inferSelect;
export type NewLagoSubscriptionRow = typeof lagoSubscriptions.$inferInsert;
export type LagoPlanRow = typeof lagoPlans.$inferSelect;
export type NewLagoPlanRow = typeof lagoPlans.$inferInsert;
export type LagoInvoiceRow = typeof lagoInvoices.$inferSelect;
export type NewLagoInvoiceRow = typeof lagoInvoices.$inferInsert;
export type LagoFeeRow = typeof lagoFees.$inferSelect;
export type NewLagoFeeRow = typeof lagoFees.$inferInsert;
export type LagoWalletRow = typeof lagoWallets.$inferSelect;
export type NewLagoWalletRow = typeof lagoWallets.$inferInsert;
export type LagoBillableMetricRow = typeof lagoBillableMetrics.$inferSelect;
export type NewLagoBillableMetricRow = typeof lagoBillableMetrics.$inferInsert;

// New sync segments emitted by the Lago reconciler. Each is its own segment
// so the SyncSegmentTabs UI can render per-entity logs and statuses.
export type LagoReconcileSegment =
  | "lago_customers"
  | "lago_subscriptions"
  | "lago_plans"
  | "lago_invoices"
  | "lago_wallets"
  | "lago_billable_metrics"
  | "local_reconcile";

export const LAGO_RECONCILE_SEGMENTS: readonly LagoReconcileSegment[] = [
  "lago_billable_metrics",
  "lago_plans",
  "lago_customers",
  "lago_subscriptions",
  "lago_invoices",
  "lago_wallets",
  "local_reconcile",
] as const;

// ============================================================================
// === ExpresScan / Wave 1 Track A: devices + device_tokens ===
//
// The iOS / future-laptop NFC reader devices that scan tap targets. Mirrors
// the migration in `drizzle/0034_devices_and_tokens.sql` exactly. The
// `tappable_devices` view (migration 0035) unions this table with
// `chargers_cache` so the scan-modal picker sees one tap-target list.
//
// Owner-role enforcement: a Postgres trigger (created in 0034) rejects
// rows whose `owner_user_id` does not reference a user with role='admin'.
// `POST /api/devices/register` MUST also reject non-admin sessions in app
// code (so the failure is a clean 403, not a constraint violation).
// ============================================================================

export const devices = pgTable("devices", {
  id: uuid("id").primaryKey().defaultRandom(),
  /** Form-factor — see `src/lib/types/devices.ts#DEVICE_KINDS`. */
  kind: text("kind").notNull(),
  /** Human-friendly label shown in admin lists + the device's own UI. */
  label: text("label").notNull(),
  /** Granted capabilities — see `DEVICE_CAPABILITIES`. */
  capabilities: text("capabilities").array().notNull().default(
    sql`ARRAY['tap']::text[]`,
  ),
  /** Admin user that owns / registered the device. Trigger enforces role='admin'. */
  ownerUserId: text("owner_user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** "ios" | "macos" | future. Free-text; trusted to the registering client. */
  platform: text("platform").notNull(),
  /** Device model identifier (e.g. "iPhone 16 Pro"). */
  model: text("model").notNull(),
  osVersion: text("os_version").notNull(),
  appVersion: text("app_version").notNull(),
  /** APNs device token (base64 / hex). NULL until first push-token PUT. */
  pushToken: text("push_token"),
  /** "sandbox" | "production" — drives APNs host selection per push. */
  apnsEnvironment: text("apns_environment"),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true }),
  /** Free-form last-known status JSON (battery, network, etc.). Best-effort. */
  lastStatus: jsonb("last_status"),
  registeredAt: timestamp("registered_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  /** Soft-delete: when set, device is hidden + bearer auth fails. */
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
  /** Set on admin force-revoke; informational (token rows are independently revoked). */
  revokedAt: timestamp("revoked_at", { withTimezone: true }),
  revokedByUserId: text("revoked_by_user_id").references(() => users.id, {
    onDelete: "set null",
  }),
}, (table) => [
  check(
    "devices_kind_check",
    sql`${table.kind} IN ('phone_nfc','laptop_nfc')`,
  ),
  check(
    "devices_apns_environment_check",
    sql`${table.apnsEnvironment} IS NULL OR ${table.apnsEnvironment} IN ('sandbox','production')`,
  ),
  index("idx_devices_owner_last_seen").on(
    table.ownerUserId,
    table.lastSeenAt.desc(),
  ).where(sql`${table.deletedAt} IS NULL`),
  index("idx_devices_last_seen").on(table.lastSeenAt.desc()).where(
    sql`${table.deletedAt} IS NULL`,
  ),
]);

export const deviceTokens = pgTable("device_tokens", {
  id: uuid("id").primaryKey().defaultRandom(),
  deviceId: uuid("device_id")
    .notNull()
    .references(() => devices.id, { onDelete: "cascade" }),
  /** sha256(rawToken) — the raw token only ever leaves on the register response. */
  tokenHash: text("token_hash").notNull().unique(),
  /**
   * Raw HMAC key (base64url, 32 random bytes). HMAC is symmetric; the server
   * must hold the raw key to verify scan-result nonces. Same threat model as
   * `STEVE_PREAUTH_HMAC_KEY` (server-resident HMAC key) — DB exfil exposes
   * forging capability per device, mitigated by per-device + per-rotation
   * scope. Migration to per-device Ed25519 (Secure-Enclave-held private key,
   * `device_pubkey` on `devices`) is the planned v2 path.
   */
  secret: text("secret").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  revokedAt: timestamp("revoked_at", { withTimezone: true }),
  lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
}, (table) => [
  index("idx_device_tokens_device").on(
    table.deviceId,
    table.createdAt.desc(),
  ),
]);

export type Device = typeof devices.$inferSelect;
export type NewDevice = typeof devices.$inferInsert;
export type DeviceToken = typeof deviceTokens.$inferSelect;
export type NewDeviceToken = typeof deviceTokens.$inferInsert;
